#!/usr/bin/env python3
"""
Resource File Generator for CPP_HTML_GEN

Downloads Bootstrap 5 and ApexCharts from CDN and converts them to C char arrays
for embedding in the HTML generator library.

Usage:
    python generate_resources.py [--output-dir <path>]

This will generate:
    - bootstrap_css.cpp
    - bootstrap_js.cpp
    - apexcharts_js.cpp
"""

import argparse
import os
import urllib.request
import sys

# CDN URLs for resources
RESOURCES = {
    'bootstrap_css': {
        'url': 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css',
        'var_name': 'bootstrap_min_css',
        'filename': 'bootstrap_css.cpp'
    },
    'bootstrap_js': {
        'url': 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js',
        'var_name': 'bootstrap_min_js',
        'filename': 'bootstrap_js.cpp'
    },
    'apexcharts_js': {
        'url': 'https://cdn.jsdelivr.net/npm/apexcharts@3.44.0/dist/apexcharts.min.js',
        'var_name': 'apexcharts_min_js',
        'filename': 'apexcharts_js.cpp'
    }
}


def download_file(url: str) -> bytes:
    """Download a file from URL and return its contents."""
    print(f"  Downloading: {url}")
    try:
        with urllib.request.urlopen(url) as response:
            data = response.read()
            print(f"  Downloaded: {len(data):,} bytes")
            return data
    except Exception as e:
        print(f"  ERROR: Failed to download {url}: {e}")
        sys.exit(1)


def bytes_to_c_array(data: bytes, var_name: str) -> str:
    """Convert bytes to a C char array string."""
    # Convert to list of signed char values (handle bytes > 127 properly)
    values = []
    for b in data:
        # Cast to signed char range (-128 to 127)
        if b > 127:
            values.append(b - 256)
        else:
            values.append(b)

    # Format as C array with 16 values per line
    lines = []
    for i in range(0, len(values), 16):
        chunk = values[i:i+16]
        line = ", ".join(str(b) for b in chunk)
        lines.append(f"        {line}")

    array_content = ",\n".join(lines)

    return f"""namespace resources {{
    const char {var_name}[] = {{
{array_content}
    }};
    const size_t {var_name}_size = sizeof({var_name});
}}
"""


def generate_cpp_file(resource_key: str, output_dir: str) -> None:
    """Generate a .cpp file for a resource."""
    resource = RESOURCES[resource_key]

    print(f"\nProcessing {resource_key}...")

    # Download the file
    data = download_file(resource['url'])

    # Convert to C array
    cpp_content = f"""/*  ===================================================================
*                      HTML Generator Library - Resources
*               Copyright 1999 - 2024 by Peter Ritter
*                A L L   R I G H T S   R E S E R V E D
*  ====================================================================
*
*  Auto-generated by tools/generate_resources.py
*  Source: {resource['url']}
*  Size: {len(data):,} bytes
*/

#include "../../include/html_resources.h"

{bytes_to_c_array(data, resource['var_name'])}
"""

    # Write to file
    output_path = os.path.join(output_dir, resource['filename'])
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(cpp_content)

    print(f"  Generated: {output_path}")
    print(f"  Array size: {len(data):,} bytes")


def main():
    parser = argparse.ArgumentParser(
        description='Generate C++ resource files from CDN downloads'
    )
    parser.add_argument(
        '--output-dir',
        default='../src/resources',
        help='Output directory for generated .cpp files'
    )

    args = parser.parse_args()

    # Resolve output directory relative to script location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.normpath(os.path.join(script_dir, args.output_dir))

    # Create output directory if needed
    os.makedirs(output_dir, exist_ok=True)

    print(f"Output directory: {output_dir}")
    print("=" * 60)

    # Generate each resource file
    for resource_key in RESOURCES:
        generate_cpp_file(resource_key, output_dir)

    print("\n" + "=" * 60)
    print("Done! Generated files:")
    for resource in RESOURCES.values():
        print(f"  - {resource['filename']}")
    print("\nRemember to update CMakeLists.txt to include these files.")


if __name__ == '__main__':
    main()
